
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.cliente (
    cliente_id bigint NOT NULL,
    contrasena character varying(255) NOT NULL,
    estado boolean NOT NULL
);


ALTER TABLE public.cliente OWNER TO "user";


CREATE TABLE public.cuenta (
    numero bigint NOT NULL,
    cliente_id bigint NOT NULL,
    estado boolean NOT NULL,
    saldo_inicial double precision NOT NULL,
    tipo character varying(255) NOT NULL
);


ALTER TABLE public.cuenta OWNER TO "user";


CREATE TABLE public.movimiento (
    id bigint NOT NULL,
    cuenta_numero bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    saldo double precision NOT NULL,
    tipo_movimiento character varying(255) NOT NULL,
    valor double precision NOT NULL
);


ALTER TABLE public.movimiento OWNER TO "user";


ALTER TABLE public.movimiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.persona (
    id bigint NOT NULL,
    direccion character varying(255),
    edad integer,
    genero character varying(255),
    identificacion character varying(255),
    nombre character varying(255) NOT NULL,
    telefono character varying(255)
);


ALTER TABLE public.persona OWNER TO "user";


ALTER TABLE public.persona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (cliente_id);



ALTER TABLE ONLY public.cuenta
    ADD CONSTRAINT cuenta_pkey PRIMARY KEY (numero);




ALTER TABLE ONLY public.movimiento
    ADD CONSTRAINT movimiento_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.persona
    ADD CONSTRAINT ukr5vsms84ih2viwd6tatk9o5pq UNIQUE (identificacion);




ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT fk33cy8185r4ecu0qd6tyra3drb FOREIGN KEY (cliente_id) REFERENCES public.persona(id);




